theme: jekyll-theme-minimal
permalink: /:categories/:year/:month/:title/
title: My Personal Website
description: A website to imporve my knowledge of github and a little bit about myself
![Cool Pic](/images/ULL.jpg)
Format: ![Alt Text](url)
